theme="nord"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
scrolloff = 10
cursorline = true
rulers = [100]
bufferline = "always"
 
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
 
[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
